eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    cache-refresh-executor-thread-pool-size: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
    
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'